[settings]
xlsx = classifier/51_FormVueLate_vue-模板结构.xlsx
section = sjtu_1_dsc
gbt = classifier/gbt4754_2017_小类.txt
batch_size = 20
retry_delay = 15
# 用哪些模型，逗号分隔，不填则用全部
models = sjtu_1_dsc, sjtu_1_dsc, llama_qwen

[sjtu_1_dsc]
base_url = https://models.sjtu.edu.cn/api/v1
api_key = sk-0evAiLlF9N7ur5RfdWDWWw
model = deepseek-chat
max_tokens = 4096

[sjtu_2_dsc]
base_url = https://models.sjtu.edu.cn/api/v1
api_key = sk-CDG-fm6660bL86AhQgfEfQ
model = deepseek-chat
max_tokens = 4096

[llama_qwen]
base_url = http://127.0.0.1:1234/v1
api-key = sk-lm-Y1V3nKtZ:9n9jtYt7KANxuMogm8O7
model = qwen2.5-14b-instruct
max_token = 4096
